### ISSUE TITLE
App Kompilieren

### ISSUE THREAD

**Issue by nilsblessing** [nilsblessing/SE_Vereinsmanager#26]
App Version v1.0 kompilieren und für die Live-Demo auf Smartphone installieren .

**Comment by nilsblessing** [comment]
App muss noch als apk umgewandelt werden für die finale Abgabe. @melaniehs @zolltben

**Comment by zolltben** [comment]
APK erstellen noch ausstehend

**Comment by nilsblessing** [comment]
Erledigt, .apk in Git-Repository abgelegt.
